version: "3.8"

services:
  app:
    container_name: securitas-app
    user: "1000:1000" # Garante que não será criado como root
    ports:
      - "8099:80" # HTTP
      - "443:443" #HTTPS
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ../src:/app
    working_dir: /app
    depends_on:
      - db
    networks:
      - securitas-net

  db:
    container_name: securitas-db
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: securitas
      POSTGRES_USER: securitas
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - securitas-net

  nginx:
    container_name: securitas-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - securitas-net

volumes:
  pgdata:

networks:
  securitas-net:
    driver: bridge
