version: '3.8'

services:
  securitas-app:
    build:
      context: ../docker
      dockerfile: Dockerfile
    container_name: securitas-app
    user: "1000:1000"
    ports:
      - "8099:80"
      - "9443:443"
    volumes:
      - ../src:/app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 300

  securitas-db:
    image: postgres:14
    container_name: securitas-db
    environment:
      POSTGRES_DB: securitas
      POSTGRES_USER: securitas_user
      POSTGRES_PASSWORD: securitas_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
